### ISSUE TITLE
Top-level linter settings are deprecated in favour of their counterparts in the `lint` section of pyproject.toml

### ISSUE THREAD

**Issue by cast42** [fpgmaas/cookiecutter-uv#11]
Issue with template https://github.com/fpgmaas/cookiecutter-uv/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml

When using ruff 0.6.5 to check my project with ```make check```:

```bash
.venv➜  uv-test-project git:(main) uv run ruff --version                        
ruff 0.6.5
```

I get the following errors:
```ascii
Checking with ruff gives:
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1
- files were modified by this hook

warning: The top-level linter settings are deprecated in favour of their counterparts in the lint section. Please update the following options in pyproject.toml:
  - 'ignore' -> 'lint.ignore'
  - 'select' -> 'lint.select'
  - 'per-file-ignores' -> 'lint.per-file-ignores'
Found 2 errors (2 fixed, 0 remaining).
```
The warning message from Ruff indicates that certain configuration options in your `pyproject.toml` file are deprecated at their current location and should be moved under a new `[tool.ruff.lint]` section. Specifically, the options `select`, `ignore`, and `per-file-ignores` need to be relocated.

Here's how you can fix the two errors in the `pyproject.toml` file:

---

### **Steps to Fix the Errors**

1. **Create a New `[tool.ruff.lint]` Section:**

   - Move the `select`, `ignore`, and `per-file-ignores` options from the `[tool.ruff]` section to a new `[tool.ruff.lint]` section.

2. **Update the Configuration Structure:**

   - The new structure will have the linter settings nested under `[tool.ruff.lint]`.

3. **Adjust the `per-file-ignores` Key:**

   - Move the `[tool.ruff.per-file-ignores]` section under `[tool.ruff.lint]`, changing its heading to `[tool.ruff.lint.per-file-ignores]`.

---

### **Updated `pyproject.toml`**

Below is the corrected version of your `pyproject.toml` file with the necessary changes applied:

```toml
[project]
name = "uv-test-project"
version = "0.0.1"
description = "This is a template repository for Python projects that use uv for their dependency management."
authors = [{ name = "Author", email = "first.author@gmail.com" }]
readme = "README.md"
keywords = ["python"]
requires-python = ">=3.9,<4.0"

[project.urls]
Homepage = "https://cast42.github.io/uv-test-project/"
Repository = "https://github.com/cast42/uv-test-project"
Documentation = "https://cast42.github.io/uv-test-project/"

[tool.uv]
dev-dependencies = [
    "pytest>=7.2.0",
    "pre-commit>=2.20.0",
    "tox-uv>=1.11.3",
    "mypy>=0.991",
    "ruff>=0.0.235",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.mypy]
files = ["uv_test_project"]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py39"
line-length = 120
fix = true

[tool.ruff.format]
preview = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E",
    "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]
```

---

### **Explanation of Changes**

1. **Moved `select` and `ignore` Options:**

   - Original location:

     ```toml
     [tool.ruff]
     select = [...]
     ignore = [...]
     ```

   - New location:

     ```toml
     [tool.ruff.lint]
     select = [...]
     ignore = [...]
     ```

2. **Moved `per-file-ignores`:**

   - Original location:

     ```toml
     [tool.ruff.per-file-ignores]
     "tests/*" = ["S101"]
     ```

   - New location:

     ```toml
     [tool.ruff.lint.per-file-ignores]
     "tests/*" = ["S101"]
     ```

3. **Reason for Changes:**

   - Ruff has deprecated top-level linter settings in favor of organizing them under the `[tool.ruff.lint]` section. This change improves the configuration structure and clarity.

4. **Other Adjustments:**

   - Removed trailing commas where unnecessary.
   - Ensured boolean values are lowercase (`true` instead of `"True"`), which is the correct syntax in TOML.

---

### **Verifying the Changes**

After updating the `pyproject.toml` file, you can verify that the warnings are resolved by re-running Ruff:

```bash
make check .
```

If you are using `pre-commit`, you can test the hooks:

```bash
pre-commit run --all-files
```

You should no longer see the warnings about deprecated top-level linter settings.

---

### **Additional Notes**

- **Boolean Values in TOML:**

  - In TOML files, boolean values should be unquoted and in lowercase (`true` or `false`), not `"True"` or `"False"`.
  - Example correction:

    ```toml
    disallow_untyped_defs = true
    ```

### **Summary**

By restructuring the `pyproject.toml` file and moving the deprecated top-level linter settings (`select`, `ignore`, `per-file-ignores`) under the `[tool.ruff.lint]` section, you comply with Ruff's updated configuration requirements. This resolves the warnings and allows Ruff to function without errors.
