### ISSUE TITLE
invalid line in on-release-main.yml

### ISSUE THREAD

**Issue by osamimi** [fpgmaas/cookiecutter-uv#37]
In `on-release-main.yml`, I think the `branches: [main]` line is not doing anything. I don't think this is valid key under 'release'. 

```
name: release-main

on:
  release:
    types: [published]
    branches: [main]
```

vscode flags this as "Unexpected value 'branches'"
